services:
  legacy-api:
    build:
      context: ./legacy-api
    container_name: legacy-api
    restart: always
    ports:
      - "4040:4040"
    networks:
      - recruitment-network

  new-recruitment-api:
    build:
      context: ./new-recruitment-api
    container_name: new-recruitment-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - legacy-api
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge